/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

dependencyLocking {
    lockAllConfigurations()
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.h2database.h2)
    api(libs.org.apache.commons.commons.dbcp2)
    api(libs.com.lowagie.itext)
    api(libs.org.codehaus.mojo.exec.maven.plugin)
    api(libs.javax.servlet.javax.servlet.api)
    testImplementation(libs.junit.junit)
}

group = "com.example"
version = "0.1.0"
description = "minitest"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
